### ISSUE TITLE
Violation of ReviOS's license

### ISSUE THREAD

**Issue by melo936** [redress-server/playbook#1]
Hi there,

It seems that the repository is not in compliance with the [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Specifically, the license has been changed to a different one and no list of changes has been provided. Therefore, we kindly request that you take immediate action to comply with the licensing requirements else we will be urged to take down the repository.

Best regards,
Revision Team

**Comment by Vichingo455** [comment]
Ok, I'm sorry for that. I will build the playbook by starting by my own.

Best regards,
Vichingo455
